theme: jekyll-theme-slate
title: "CyberSecurity & DevSecOps Expert: Develop, PenTest, and Deploy Secure Applications"
description: "Become a CyberSecurity & DevSecOps Specialist: Understand the risks of an application to prioritize tests and corrections; Conduct a Web/API application Pentest"
url: "https://www.ilaria-academy.com/nextjob/appsec-cybersecurity-hacker/en/"
show_downloads: false
